### PR TITLE
Fix sm_rndclass command

### PR DESCRIPTION
**Pull request by doomy64**
Fix sm_rndclass command
sm_rndclass now updates PDA and watch slots to prevent other classes from having them. This also prevents having an engi/spy with no PDA.

### CODE REVIEW

**Comment by doomy64** [comment]
I'm not sure why github says compile is failing. The errors are coming from stocks.sp, which I left unmodified.

**Review by FortyTwoFortyTwo — CHANGES_REQUESTED** [review]
Change looks fine for `Mode_Normal` and `Mode_NormalRound`, but `Mode_Team` and `Mode_All` was unchanged, i'd like to see both take into account with PDA slots, updating `g_iTeamWeaponIndex` along with `g_iTeamClass`

**Comment by doomy64** [comment]
The command should now work properly with `Mode_Team` and `Mode_All` now

**Review by FortyTwoFortyTwo — APPROVED** [review]
I might improve this code later, but this should work anyway.
I've been wanting to have this fix when debugging engineer and spy class, thanks!

**Pull request merged**
